### ISSUE TITLE
speech_cmdline is broken on windows

### ISSUE THREAD

**Issue by aerostitch** [aerostitch/testnavit#37]
*Issue migrated from trac ticket # 615*

**component:** port/windows | **priority:** major

#### 2010-07-08 21:58:55: richt created the issue

___
> speech_cmdline sigsevs on Windows - it looks like an ANSI/Unicode problem.
> 
> ```
> #0  0x7584f5cd in KERNEL32CreateProcessInternalW ()
>    from C:\Windows\system32\kernel32.dll
> #1  0x12205fec in ?? ()
> #2  0x032abbfc in ?? ()
> #3  0x757f208e in KERNEL32CreateProcessAsUserW ()
>    from C:\Windows\system32\kernel32.dll
> #4  0x68a41309 in speechd_say (this=0x32ac380,
>     text=0x343c610 "Turn left soon") at speech_cmdline.c:94
> #5  0x69cefef7 in speech_say (this_=0x32a9d58,
>     text=0x343c610 "Turn left soon") at speech.c:80
> #6  0x69cd8bfa in navit_speak (this_=0x6dc720) at navit.c:1011
> #7  0x69cc4bc8 in callback_call (cb=0x3374d30, pcount=1, p=0x22f2e0)
>     at callback.c:178
> #8  0x69cc4d23 in callback_list_call_attr (l=0x6dbee8, type=attr_any,
>     pcount=1, p=0x22f2e0) at callback.c:219
> #9  0x69cc4df8 in callback_list_call (l=0x6dbee8, pcount=1, p=0x22f2e0)
>     at callback.c:241
> ```

**Comment by aerostitch** [comment]
#### 2011-05-26 13:13:34: heinold@inf.fu-berlin.de commented


___
> Hi,
> 
> this should be fixed now with the latest patches from
> http://trac.navit-project.org/ticket/461. Please test it
> and report.
> 
> Bye Henning
